### ISSUE TITLE
Issue running npx unframer

### ISSUE THREAD

**Issue by britzdylan** [remorses/unframer#12]
Node: v20.11.0
Frame work: Astro + React

I followed all the steps outlined in the docs and this issue is what pops up when I try and run `npx unframer.`

```
[unframer] Error processing config Error: Command failed: node --input-type=module -e 'import("D:\\framer-astro\\src\\framer\\Button.js").then(x => { console.log("__delimiter__"); console.log(JSON.stringify({propertyControls: x.default?.propertyControls, fonts: x?.default?.fonts } || {}, null, 2))
        })'
file:///D:/framer-astro/[eval1]:1
'import(D:\\framer-astro\\src\\framer\\Button.js).then(x
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid or unexpected token
    at ModuleLoader.evalInstance (node:internal/modules/esm/loader:203:22)
    at new ModuleJob (node:internal/modules/esm/module_job:65:26)
    at ModuleLoader.eval (node:internal/modules/esm/loader:215:17)
    at node:internal/process/execution:56:55
    at loadESM (node:internal/process/esm_loader:28:13)
    at evalModule (node:internal/process/execution:56:28)
    at node:internal/main/eval_string:30:3

Node.js v20.11.1
'{}' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
```

**Comment by remorses** [comment]
Should be fixed in `2.2.0` can you try again?

```
npx unframer@latest
```

**Comment by britzdylan** [comment]
Got some **widows-specific** errors now with Node:

```
[unframer] Error processing config Error: Command failed: "C:\\Program Files\\nodejs\\node.exe" --input-type=module -e "import(\"D:\\\\framer-astro\\\\src\\\\framer\\\\Divider.js\").then(x => { console.log(\"__delimiter__\"); console.log(JSON.stringify({propertyControls: x.default?.propertyControls, fonts: x?.default?.fonts } || {}, null, 2)) })"
node:internal/modules/esm/load:239
    throw new ERR_UNSUPPORTED_ESM_URL_SCHEME(parsed, schemes);
          ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:239:11)
    at defaultLoad (node:internal/modules/esm/load:130:3)
    at ModuleLoader.load (node:internal/modules/esm/loader:409:13)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:56)
    at new ModuleJob (node:internal/modules/esm/module_job:65:26)
    at #createModuleJob (node:internal/modules/esm/loader:303:17)
    at ModuleLoader.getJobFromResolveResult (node:internal/modules/esm/loader:260:34)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:241:17)
    at async ModuleLoader.import (node:internal/modules/esm/loader:328:23) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}

Node.js v20.11.1

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
```

This seems to be a Node issue on v20, I upgraded to v21 and it still persists.

**Comment by remorses** [comment]
I updated the code to use `file://` can you try now?

**Comment by britzdylan** [comment]
Wokring!
